### ISSUE TITLE
How to debug UI issues inside the wallet

### ISSUE THREAD

**Issue by kohlivarun5** [CoinbaseWallet/toshi-ios-client#913]
I have a Dapp that functions fine in Chrome and Firefox on my Mac, but when I try it inside iOS in the app, it has some issues. 

I have a hunch it has to do with WebView (if Toshi uses that), but I am unable to see anything (such as console).

What is the suggested way of debugging apps running inside the wallet ?

**Comment by designatednerd** [comment]
It does use WKWebView - you should be able to attach to it with developer options enabled in Safari. You may need to be running the app in debug mode from Xcode to be able to do this, but I'd try just attaching through Safari first.

**Comment by kohlivarun5** [comment]
Thanks, yes, that worked. Had to do it through Xcode
